clear % clear existing variables
clc % clear screen

direc = '/home/pablo/disco2/proyectos/2019-ANTI-vea-EEG-FerL';
addpath /home/usuario/Descargas/eeglab2019_1


subjects = {'1'; ...
            '2'; ...
            '4'; ...
            '6'; ...
            '9'; ...
            '10'; ...
            '12'; ...   
            '13'; ...
            '16'; ...
            '17'; ...
            '18'; ...
            '19'; ...
            '20'; ...
            '21'; ...
            '22'; ...
            '23'; ...
            '24'; ...
            '28'; ...
            '30'; ...
            '40'; ...
            '41'; ...
            '42'; ...
            '43'; ...
            '44'; ...
            '45'; ...
            '46'; ...
            '47'; ...
            '48'; ...
            '49'; ...
            '50'; ...
            '51'; ...
            '52'; ...
            '53'; ...
            '54'; ...
            '55'; ...
            '56'; ...
            '58'; ...
            };% missing participant 60


eeglab,
close % closes the window opened for eeglab
%% 
hpfreq = 0.5;    

lpfreq = 45;
Npartic = size(subjects,1)
%% 

for participant = 1:Npartic
    
    for ses = 1:2
        disp(['leyendo sujeto numero ', num2str(participant),' de ' num2str(size(subjects,1))]) %concatenate to display and inform the current process
        EEG = pop_biosig(fullfile(direc,'data','bdf', ['ANTIVEA_', '_part', subjects{participant},'_ses', num2str(ses), '.bdf'])); % pop_biosig to read the file
        

        EEG.setname = ['ANTIVEA_', '_part', subjects{participant},'_ses', num2str(ses)];
        EEG = eeg_checkset( EEG ); % updates something unknown

        if not(EEG.srate == 512)
            EEG = pop_resample(EEG,512); %pop_resample to increase/decrease the sample rate
            EEG = eeg_checkset( EEG );
        end
        
        % pop_select to select the firsts X channels
        EEG = pop_select( EEG, 'channel',1:128);
        EEG = eeg_checkset( EEG );
        
        disp('referencia al promedio') 
        EEG = pop_reref( EEG, []);
        EEG.ref = 'averef';
        
        disp('carga posiciones de canales')    
        EEG=pop_chanedit(EEG,  'load',{fullfile(direc,'scripts','coord2.sph'), 'filetype', 'sph'});
        EEG = eeg_checkset( EEG );
        
        disp('filtra')    
        EEG = pop_eegfiltnew(EEG, hpfreq, lpfreq);


        EEG = pop_saveset( EEG,  'filename',['ANTIVEA_', '_part', subjects{participant},'_ses', num2str(ses)], 'filepath',fullfile(direc,'data','set') ); 
        EEG = eeg_checkset( EEG );
        clear EEG
    end
end

disp('terminado')

<<<<<<< Updated upstream
=======

>>>>>>> Stashed changes
